### ISSUE TITLE
Grid controller's documentation and constructors need cleanup

### ISSUE THREAD

**Issue by ctgraham** [pkp/staticPages#19]
There are useless constructors:
https://github.com/pkp/staticPages/blob/42cfa1a47e11fe7a795f7ba4f9bc9163daca8e31/controllers/grid/StaticPageGridCellProvider.inc.php#L20-L25
And typos in the documentation:
https://github.com/pkp/staticPages/blob/42cfa1a47e11fe7a795f7ba4f9bc9163daca8e31/controllers/grid/StaticPageGridHandler.inc.php#L48
https://github.com/pkp/staticPages/blob/42cfa1a47e11fe7a795f7ba4f9bc9163daca8e31/controllers/grid/StaticPageGridHandler.inc.php#L100

**Comment by asmecher** [comment]
Looks like this already got merged -- closing.
