### ISSUE TITLE
The StaticPageForm is out of sync with the parent Form method declarations.

### ISSUE THREAD

**Issue by ctgraham** [pkp/staticPages#21]
See:
https://github.com/pkp/staticPages/blob/42cfa1a47e11fe7a795f7ba4f9bc9163daca8e31/controllers/grid/form/StaticPageForm.inc.php#L29-L35
vs.
https://github.com/pkp/pkp-lib/blob/300c6764370180d0ffb8fd151b4afa414049d009/classes/form/Form.inc.php#L85-L89

and 

https://github.com/pkp/staticPages/blob/42cfa1a47e11fe7a795f7ba4f9bc9163daca8e31/controllers/grid/form/StaticPageForm.inc.php#L101-L104
vs.
https://github.com/pkp/pkp-lib/blob/300c6764370180d0ffb8fd151b4afa414049d009/classes/form/Form.inc.php#L302-L308

**Comment by asmecher** [comment]
The constructor is OK to have a different set of parameters, and the `Form::execute` mismatch was corrected as part of https://github.com/pkp/pkp-lib/commit/016c8c1f4edc8c69ba191bb3044d39dc1170ed98.
