### ISSUE TITLE
Possible unnecessary code duplication

### ISSUE THREAD

**Issue by MarHerUMR** [pkp/staticPages#24]
Hey,

in the StaticPageForm there seems to be a unnecessary code duplication in the fetch method.

On the lines 80 - 87 smarty variables get assigned when $request->getContext(); is not falsy.

On the lines 89 - 96 the same things happen.

Is there a reason for the second time of setting the variables?

**Comment by asmecher** [comment]
Thanks for the heads-up, @MarHerUMR. Removed.
